=pod

=head1 NAME

Data::Selectable - Perl extension for XPath like accessing from complex data structures

=head1 SYNOPSIS

  use Data::Selectable ();

  my $data = {
    result => {
      msg => [
        { text => 'msg0' },
        { text => 'msg1' },
        { text => 'msg2' }
      ]
    }
  };

  my $self = Data::Selectable->new( $data );

  # "msg1"
  my $value  = $self->select( '/result/msg[1]/text' );

  my $self = Data::Selectable->new( $data, $callback );

=head1 DESCRIPTION

XPath like access to select values from a complex data structures.

C<hash_value_is_undefined> / C<array_value_is_undefined> are only called if it was not
the last part of the path.  If the last part of path is not exists C<undef>
is returned.

=head2 CALLBACKs

The default callbacks but you can overwrite them.

  {
    hash_value_is_undefined => sub {
      my ( $path, $data, $key ) = @_;
      croak "Value for hash key '$key' is undefined"
    },
    array_value_is_undefined => sub {
      my ( $path, $data, $index ) = @_;
      croak "Value for array index $index is undefined"
    },
    retrieve_key_from_non_hash => sub {
      my ( $path, $data, $key ) = @_;
      croak "Try to retrieve a hash key '$key' from a ${ \( reftype $data ) } reference"
    }
    retrieve_index_from_non_array => sub {
      my ( $path, $data, $index ) = @_;
      croak "Try to retrieve an array index $index from a ${ \( reftype $data ) } reference"
    }
  }

=head1 SEE ALSO

=over

=item *

L<Data::Path>

=item *

L<Data::DPath>

=item *

L<Data::Nested>

=item *

L<Data::SelectableSimple>

=item *

L<Data::SPath>

=item *

L<Data::SimplePath>

=item *

L<JSON::Path>

=item *

L<JSONPath|https://www.rfc-editor.org/info/rfc9535/>

=back

=head1 AUTHOR

Sven Willenbuecher <sven.willenbuecher@gmx.de>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2026 by Sven Willenbuecher.

This is free software; you can redistribute it and/or modify it under the
same terms as the Perl 5 programming language system itself.

=cut
